name: set-env-and-add-path

on: 
  push:
 
  useenv:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: use the ENV YML tag
      env:
        REPO_NAME: ${{ github.event.repository.name }}
      run: |
        echo $REPO_NAME
