name: midnight

on: 
  push:
 
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/setup-python@v1.1.1
    - name: Install latest python dependencies
      run: | 
        python -m pip install --upgrade pip 
        pip install gitpython
    - uses: actions/checkout@v1
    - name: Find and mirror a list of public repos
      env:
      run: |
        cd ..
        python3 ${{ github.event.repository.name }}/testGitPython.py
        cd ${{ github.event.repository.name }}

