name: set-env-and-add-path

on: 
  push:
 
jobs:
  gitPython:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/setup-python@v1.1.1
    - name: Install latest python dependencies
      run: | 
        python -m pip install --upgrade pip 
        pip install gitpython
    - uses: actions/checkout@v1
    - name: Run a Python script that uses gitpython
      run: |
        cd ..
        python3 ${{ github.event.repository.name }}/testGitPython.py
        cd ${{ github.event.repository.name }}

  useenv:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: use the ENV YML tag
      env:
        REPO_NAME: ${{ github.event.repository.name }}
      run: |
        echo $REPO_NAME

